version: "3.3"

services:
  rabbitmq:
    image: "rabbitmq:3.8.5-management-alpine"
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: "redis:alpine3.12"
    ports:
      - "6379:6379"
    env_file:
      - variables.env

  service:
    container_name: accp
    build: ./
    image: soldatov-s/acc
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - variables.env
    command: serve
    ports:
      - "9000:9000"
      - "9100:9100"
    restart: on-failure
